# Generated by Django 5.2.8 on 2026-10-03 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='SecurityAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('user_created', 'User created'), ('invite_sent', 'Invite sent'), ('password_setup_completed', 'Password setup completed'), ('password_reset_requested', 'Password reset requested'), ('password_reset_completed', 'Password reset completed'), ('password_changed', 'Password changed'), ('account_disabled', 'Account disabled'), ('account_reactivated', 'Account reactivated'), ('role_changed', 'Role changed')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['target_user', 'timestamp'], name='accounts_se_target__4c16b9_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_se_action_e236e0_idx')],
            },
        ),
    ]
