# Generated by Django 5.2.8 on 2026-10-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auth_version_securityauditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provisioning_data',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
