# Generated by Django 5.2.8 on 2026-10-02 08:03

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schedule', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.department'),
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_student_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_parent_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=16)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.batch')),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.course')),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.batch')),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['course', 'status'], name='academics_b_course__3b0921_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('institution'), condition=models.Q(('status', 'active')), name='academics_active_batch_tenant_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('status', 'active')), models.Q(('archived_at__isnull', False), ('status', 'archived')), _connector='OR'), name='academics_batch_archive_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['institution', 'is_active'], name='academics_d_institu_ebeb59_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('institution'), name='academics_department_tenant_code_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department', 'is_active'], name='academics_c_departm_d213d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('institution'), name='academics_course_tenant_code_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='parentstudentlink',
            index=models.Index(fields=['parent'], name='academics_p_parent__d955e6_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentlink',
            index=models.Index(fields=['student'], name='academics_p_student_82a66b_idx'),
        ),
        migrations.AddIndex(
            model_name='parentstudentlink',
            index=models.Index(fields=['institution'], name='academics_p_institu_0fdc7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentstudentlink',
            constraint=models.UniqueConstraint(fields=('parent', 'student'), name='academics_parent_student_unique'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'status'], name='academics_s_student_7ca871_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('batch', 'student'), name='academics_batch_student_unique'),
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('removed_at__isnull', True), ('status', 'active')), models.Q(('removed_at__isnull', False), ('status', 'removed')), _connector='OR'), name='academics_enrollment_removal_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['institution', 'is_active'], name='academics_s_institu_9f625f_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('course'), name='academics_subject_course_code_ci_unique'),
        ),
        migrations.AddIndex(
            model_name='teacherassignment',
            index=models.Index(fields=['teacher', 'is_active'], name='academics_t_teacher_3f2cd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('batch', 'teacher', 'subject'), name='academics_teacher_batch_subject_unique'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', True)), fields=('batch', 'teacher'), name='academics_teacher_batch_general_unique'),
        ),
    ]
