# Generated by Django 5.2.8 on 2026-10-02 09:04

import apps.resources.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_user_role_integrity_trigger'),
        ('accounts', '0001_initial'),
        ('learning', '0003_fix_shared_trigger_column_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(editable=False, max_length=500, upload_to=apps.resources.models.resource_upload_path)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='academics.batch')),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_resources', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_learning_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'created_at'], name='resources_l_batch_i_c9c563_idx')],
                'constraints': [models.UniqueConstraint(fields=('file',), name='resources_learning_file_path_unique')],
            },
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(editable=False, max_length=500, upload_to=apps.resources.models.note_upload_path)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_files', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.studentnote')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('file',), name='resources_note_file_path_unique')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(editable=False, max_length=500, upload_to=apps.resources.models.submission_upload_path)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='learning.submission')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_submission_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['submission', 'created_at'], name='resources_s_submiss_2f83de_idx')],
                'constraints': [models.UniqueConstraint(fields=('file',), name='resources_submission_file_path_unique')],
            },
        ),
    ]
