# Generated by Django 5.2.8 on 2026-10-02 09:11

import apps.resources.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('learning', '0003_fix_shared_trigger_column_access'),
        ('resources', '0002_resource_integrity_triggers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('mime_type', models.CharField(editable=False, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(editable=False, max_length=500, upload_to=apps.resources.models.assignment_upload_path)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='learning.assignment')),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_assignment_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['assignment', 'created_at'], name='resources_a_assignm_d40225_idx')],
                'constraints': [models.UniqueConstraint(fields=('file',), name='resources_assignment_file_path_unique')],
            },
        ),
    ]
