# Generated by Django 5.2.8 on 2026-10-02 09:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('target', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.dailygoal')),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('goal_created', 'Goal created'), ('goal_completed', 'Goal completed'), ('task_created', 'Task created'), ('task_completed', 'Task completed')], max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('institution', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='accounts.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity_events', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='tracker.dailygoal')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='tracker.dailytask')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailygoal',
            index=models.Index(fields=['student', 'status'], name='tracker_dai_student_61d02f_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailygoal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('completed_at__isnull', True), ('status__in', ('active', 'archived'))), _connector='OR'), name='tracker_goal_completion_consistent'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['student', '-activity_date'], name='tracker_dai_student_3aedeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailytask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('completed_at__isnull', True), ('status', 'pending')), _connector='OR'), name='tracker_task_completion_consistent'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['student', '-occurred_at'], name='tracker_act_student_542aa2_idx'),
        ),
    ]
